### PR TITLE
update node-sass

### PR DESCRIPTION
**Pull request by JoeChapman**
Update to hof 6.2.0 and latest node-sass

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Wouldn't 3.4.2 be better than a beta of 3.5?
Or we could wait until my PR is merged in on passports-frontend-toolkit...

**Comment by joefitter** [comment]
Yeah I think we should go with `3.4.2` - I added 3.5.0-beta-1 in gro but not really sure what I was thinking...!

**Comment by daniel-ac-martin** [comment]
The PR I referred to: https://github.com/UKHomeOffice/passports-frontend-toolkit/pull/43

**Comment by daniel-ac-martin** [comment]
If we update to hmpo-frontend-toolkit v3.1.1 then we should now be able to update node-sass to v3.6.0.

**Comment by daniel-ac-martin** [comment]
And the ^ can be reinstated of course.

**Comment by daniel-ac-martin** [comment]
@JoeChapman: We should make a new PR for this stuff to reinstate the caret and upgrade hmpo-frontend-toolkit.

**Comment by easternbloc** [comment]
@JoeChapman why did you self merge this?

The fix in frontend toolkit would have fixed this.

**Pull request merged**
