### PR TITLE
Replaced parallelshell (deprecated) with npm-run-all, also removed unn…

### PR DESCRIPTION
**Pull request by joefitter**
…ec path for node-sass exec #31

### CODE REVIEW

**Comment by easternbloc** [comment]
Please rebase this PR we try not to allow merge commits to get into PR's

**Comment by easternbloc** [comment]
@joefitter also please try and follow this commit style https://github.com/alphagov/styleguides/blob/master/git.md

**Comment by JoeChapman** [comment]
@joefitter we will can go over this at Monday's ways of working meeting, in the interim: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by joefitter** [comment]
Brill article - I have always used the -m flag and squashed commit messages. Thanks for this!

**Pull request merged**
