### PR TITLE
Updated to remove empty header tags. Addresses issue #10

### PR DESCRIPTION
**Pull request by timgent**
https://github.com/UKHomeOffice/hof-example-form/issues/10

### CODE REVIEW

**Comment by JoeChapman** [comment]
Cool Tim, is it documented?

**Comment by timgent** [comment]
No.... good point. Happy with me adding into docs [here](https://github.com/UKHomeOffice/hof/blob/master/documentation/views.md)?

**Comment by easternbloc** [comment]
@timgent this still needs some docs to get merged. :love_letter:

**Comment by JoeChapman** [comment]
@timgent docs^^^^^^^^^^^^^^^

**Pull request closed without merging**
