### PR TITLE
Use new node docker image

### PR DESCRIPTION
**Pull request by JoeChapman**
- extend from quay.io/ukhomeofficedigital/nodejs:v4.4.2
- add .dockerignore
- update to latest HOF
- fix docker-compose environment

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
We should probably remove run.sh now that it's redundant.
docker-compose isn't entirely fixed as it doesn't serve the static assets. - Would be nice to get nginx in there.
docker-compose is also using "net: host" which would be nice to avoid. (Though we might need it for nginx.)

**Comment by daniel-ac-martin** [comment]
But otherwise LGTM. :-)

**Comment by JoeChapman** [comment]
Node is serving the static assets. Allan has suggested we only use nginx to cache the static assets

**Comment by daniel-ac-martin** [comment]
Apologies I was just missing the CSS due to the node-sass issue!

**Pull request merged**
