### PR TITLE
Chore/cleanup update

### PR DESCRIPTION
**Pull request by JoeChapman**
use the latest middleware
use hof v8

### CODE REVIEW

**Comment by joefitter** [comment]
FAIL

**Comment by joefitter** [comment]
Ah - looks like its the npm issue

**Comment by joefitter** [comment]
LGTM

**Comment by JoeChapman** [comment]
@easternbloc, @daniel-ac-martin @bendiggle @gxxm please check this makes sense

**Comment by gxxm** [comment]
LGTM

**Comment by easternbloc** [comment]
> Ah - looks like its the npm issue

Have we documented somewhere what the npm issue is for people who might bump into this?

**Comment by JoeChapman** [comment]
I will document it on example form

**Comment by joefitter** [comment]
Personally I think we are going about this the wrong way - fixing a problem by saying you can't use npm@2 isn't a solution. This should ideally be fixed at source

**Comment by daniel-ac-martin** [comment]
Indeed.
Do we know the actual cause yet? Is it the shrink-wrap?

**Comment by daniel-ac-martin** [comment]
BTW, upgrading HOF means we don't need to pin node-sass any more.

**Comment by daniel-ac-martin** [comment]
And does the problem still exist with the new shrink-wrap? - https://github.com/UKHomeOffice/hof-example-form/pull/63

**Comment by joefitter** [comment]
its a problem with hmpo-fronend-toolkit, not shrinkwrapping, It broke between 4.0 and 4.1.0

**Comment by JoeChapman** [comment]
> Personally I think we are going about this the wrong way - fixing a problem by saying you can't use npm@2 isn't a solution. This should ideally be fixed at source

True but all build were already failing and I thought it pertinent to update the example form with the new middleware  implementation of risk others not being abke to use the example form

**Comment by joefitter** [comment]
@JoeChapman yes - deffo in this case, I was just saying we should still try and fix if we ca

**Comment by JoeChapman** [comment]
> BTW, upgrading HOF means we don't need to pin node-sass any more.

Upgrading to v8?

**Comment by joefitter** [comment]
We could fix by pinning hof to the last working version - 4.0.0

**Comment by daniel-ac-martin** [comment]
> > BTW, upgrading HOF means we don't need to pin node-sass any more.
> 
> Upgrading to v8?

v7. :-)

Updated my old PR: https://github.com/UKHomeOffice/hof-example-form/pull/47

**Pull request merged**
