### PR TITLE
Feature/upate

### PR DESCRIPTION
**Pull request by JoeChapman**
Rename .jscsrc and update contents
update to latest hof
add middleware
remove hogan.js
update ignore files
remove error handler

### CODE REVIEW

**Comment by JoeChapman** [comment]
@joefitter @easternbloc @gxxm this is just a small clean up. I am making incremental updates to the repo to bring it in line with HOF. Please take a quick look

**Comment by JoeChapman** [comment]
@joefitter @easternbloc @daniel-ac-martin @gxxm please look at this and feedback.

**Comment by joefitter** [comment]
This gets my seal of approval :neckbeard:

**Comment by gxxm** [comment]
LGTM

**Pull request merged**
